-- require("config.plugins.gitsigns")
-- require("config.core.colorscheme")
require("config.lazy")
require("config.core.options")
require("config.core.keymaps")
require("config.plugins.nvim-tree")
require("config.plugins.comment")
require("config.plugins.lualine")
require("config.plugins.telescope")
require("config.plugins.nvim-cmp")
require("config.plugins.lsp.mason")
require("config.plugins.lsp.lspsaga")
require("config.plugins.lsp.lspconfig")
require("config.plugins.lsp.null-ls")
require("config.plugins.autopairs")
require("config.plugins.treesitter")
require("config.plugins.nvimtsautotag")
require("config.plugins.lsp.lspsignature")
require("config.plugins.catppuccin")
require("config.plugins.dashboard")
